version: "3.9"  #首先是版本号，别乱写，这个是和Docker版本有对应的
services: #services里面就是我们所有需要进行编排的服务了
  spring: #服务名称，随便起
    container_name: app_springboot  #一会要创建的容器名称
    build: .
    ports:
      - "8080:8080"
    depends_on: #这里设置一下依赖，需要等待mysql启动后才运行，但是没啥用，这个并不是等到启动完成后，而是进程建立就停止等待
      - mysql
    restart: always  #这里配置容器停止后自动重启
  mysql:
    container_name: app_mysql
    image: mysql/mysql-server:8.0.30
    volumes:
      - /apps/mysql/mydir:/mydir
      - /apps/mysql/datadir:/var/lib/mysql
      - /apps/mysql/conf/my.cnf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - /apps/mysql/source:/docker-entrypoint-initdb.d
    environment: #这里我们通过环境变量配置MySQL的root账号和密码
      MYSQL_ROOT_HOST: '%'   #登陆的主机，这里直接配置为'%'
      MYSQL_ROOT_PASSWORD: '1213707943'    #MySQL root账号的密码，别设定得太简单了
      MYSQL_DATABASE: 'school_cat'    #在启动时自动创建的数据库
      TZ: 'Asia/Shanghai'    #时区
    ports:
      - "3306:3306"
  redis:
    container_name: app_redis
    image: redis:latest
    command: redis-server --requirepass 1213707943
    ports:
      - "6379:6379"